// Icon registry so server components can reference icons by name when
// rendering client components (component functions can't cross the
// RSC boundary as props).
import {
  BarChart3,
  BookOpen,
  Boxes,
  BriefcaseBusiness,
  Building2,
  Bus,
  CalendarClock,
  CalendarDays,
  ClipboardCheck,
  ClipboardList,
  DoorOpen,
  FileSpreadsheet,
  GraduationCap,
  HandCoins,
  IndianRupee,
  LayoutDashboard,
  Megaphone,
  MessageSquare,
  NotebookPen,
  School,
  Settings,
  UserPlus,
  UserRound,
  Users,
  Wallet,
} from "lucide-react";

export const ICONS = {
  BarChart3,
  BookOpen,
  Boxes,
  BriefcaseBusiness,
  Building2,
  Bus,
  CalendarClock,
  CalendarDays,
  ClipboardCheck,
  ClipboardList,
  DoorOpen,
  FileSpreadsheet,
  GraduationCap,
  HandCoins,
  IndianRupee,
  LayoutDashboard,
  Megaphone,
  MessageSquare,
  NotebookPen,
  School,
  Settings,
  UserPlus,
  UserRound,
  Users,
  Wallet,
} as const;

export type IconName = keyof typeof ICONS;
